apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
  labels:
    type: local
spec:
  storageClassName: retain
  capacity:
    storage: 8Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: /data/mongo
