apiVersion: v1
kind: Service
metadata:
  name: {{ template "mongo.fullname" . }}
  labels:
    app: {{ template "mongo.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
  selector:
    app: {{ template "mongo.fullname" . }}
