apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
data:
  password: cGFzc3dvcmQK # base64 encryption for 'password'
  #password: cEBzU3cwcmQK # base64 encryption for 'p@sSw0rd' Test for rolling update.
