apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
data:
  #password: cGFzc3dvcmQK # base64 encryption for 'password'
  password: cEBzCg== # base64 encryption for 'p@s$w0rd' Test for rolling update.
