apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  volumes:
  - name: pgdata
    persistentVolumeClaim:
     claimName: pg-data-claim
  containers:
  - name: postgres
    image: postgres
    ports:
    - containerPort: 5432
    name: postgres
    volumeMounts:
    - mountPath: "/var/lib/postgresql/data"
    name: pgdata
    env:
    - name: POSTGRES_USER
      valueFrom:
       configMapKeyRef:
        name: postgres-secret
       key: postgres_user
    - name: POSTGRES_PASSWORD
      valueFrom:
       configMapKeyRef:
        name: postgres-secret
       key: postgres_password

