apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  containers:
    -name: postgres
    image: postgres
    command: ["sudo -u postgres CREATE USER $USERNAME WITH PASSWORD $PASSWORD;"]
    command: ["sudo -u postgres createdb $DATABASE"]
    command: ["sudo -u postgres grant all privileges on database $DATABASE to $USERNAME"]
    env:
      name: USERNAME
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: username
      name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password
      name: DATABASE
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: database
