apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  containers:
    - name: postgres
    image: postgres
    env:
      - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: username
      - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password
