apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-data
  labels:
    type: local
spec:
  storageClassName: retain
  capacity:
    storage: 5Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: /data/pg
